
/**
 * 
 * 地区分组数据
 */
export type RegionGroup = {
    label: string
    options: {
        code: string
        name: string
    }[]
}

export const regionGroups: RegionGroup[] = [
    {
        label: "热门地区",
        options: [{
            code: "US",
            name: "美国"
        }, {
            code: "JP",
            name: "日本"
        }, {
            code: "KR",
            name: "韩国"
        }, {
            code: "TH",
            name: "泰国"
        }, {
            code: "TW",
            name: "台湾"
        }, {
            code: "BR",
            name: "巴西"
        }]
    },
    {
        label: "欧洲地区",
        options: [{
            code: "FR",
            name: "法国"
        }, {
            code: "SE",
            name: "瑞典"
        }, {
            code: "RU",
            name: "俄罗斯"
        }, {
            code: "ES",
            name: "西班牙"
        }, {
            code: "IS",
            name: "冰岛"
        }, {
            code: "GB",
            name: "英国"
        }, {
            code: "IE",
            name: "爱尔兰"
        }, {
            code: "DE",
            name: "德国"
        }, {
            code: "LI",
            name: "列支敦士登"
        }, {
            code: "BG",
            name: "保加利亚"
        }, {
            code: "CH",
            name: "瑞士"
        }, {
            code: "IT",
            name: "意大利"
        }, {
            code: "MT",
            name: "马耳他"
        }, {
            code: "AD",
            name: "安道尔共和国"
        }, {
            code: "EE",
            name: "爱沙尼亚"
        }, {
            code: "GR",
            name: "希腊"
        }, {
            code: "YU",
            name: "南斯拉夫"
        }, {
            code: "LT",
            name: "立陶宛"
        }, {
            code: "SI",
            name: "斯洛文尼亚"
        }, {
            code: "LU",
            name: "卢森堡"
        }, {
            code: "AL",
            name: "阿尔巴尼亚"
        }, {
            code: "SK",
            name: "斯洛伐克"
        }, {
            code: "FI",
            name: "芬兰"
        }, {
            code: "LV",
            name: "拉脱维亚"
        }, {
            code: "TR",
            name: "土耳其"
        }, {
            code: "PL",
            name: "波兰"
        }, {
            code: "SM",
            name: "圣马力诺"
        }, {
            code: "HU",
            name: "匈牙利"
        }, {
            code: "MC",
            name: "摩纳哥"
        }, {
            code: "AT",
            name: "奥地利"
        }, {
            code: "PT",
            name: "葡萄牙"
        }, {
            code: "CY",
            name: "塞浦路斯"
        }, {
            code: "MD",
            name: "摩尔多瓦"
        }, {
            code: "CZ",
            name: "捷克"
        }, {
            code: "UA",
            name: "乌克兰"
        }, {
            code: "BY",
            name: "白俄罗斯"
        }, {
            code: "NL",
            name: "荷兰"
        }, {
            code: "RO",
            name: "罗马尼亚"
        }, {
            code: "NO",
            name: "挪威"
        }, {
            code: "DK",
            name: "丹麦"
        }, {
            code: "BE",
            name: "比利时"
        }, {
            code: "GI",
            name: "直布罗陀"
        }, {
            code: "AM",
            name: "亚美尼亚"
        }, {
            code: "GE",
            name: "格鲁吉亚"
        }, {
            code: "VA",
            name: "梵蒂冈"
        }, {
            code: "ME",
            name: "黑山共和国(黑山)"
        }, {
            code: "XK",
            name: "科索沃"
        }, {
            code: "MK",
            name: "马其顿"
        }, {
            code: "BA",
            name: "波黑共和国(波黑)"
        }, {
            code: "HR",
            name: "克罗地亚"
        }, {
            code: "RS",
            name: "塞尔维亚"
        }]
    },
    {
        label: "亚洲地区(除了东南亚)",
        options: [{
            code: "LK",
            name: "斯里兰卡"
        }, {
            code: "TJ",
            name: "塔吉克斯坦"
        }, {
            code: "AF",
            name: "阿富汗"
        }, {
            code: "TM",
            name: "土库曼斯坦"
        }, {
            code: "GU",
            name: "关岛"
        }, {
            code: "KG",
            name: "吉尔吉斯坦"
        }, {
            code: "PK",
            name: "巴基斯坦"
        }, {
            code: "KP",
            name: "朝鲜"
        }, {
            code: "KW",
            name: "科威特"
        }, {
            code: "QA",
            name: "卡塔尔"
        }, {
            code: "UG",
            name: "乌干达"
        }, {
            code: "IL",
            name: "以色列"
        }, {
            code: "IN",
            name: "印度"
        }, {
            code: "BD",
            name: "孟加拉国"
        }, {
            code: "SY",
            name: "叙利亚"
        }, {
            code: "IQ",
            name: "伊拉克"
        }, {
            code: "LB",
            name: "黎巴嫩"
        }, {
            code: "MN",
            name: "蒙古"
        }, {
            code: "NP",
            name: "尼泊尔"
        }, {
            code: "SA",
            name: "沙特阿拉伯"
        }, {
            code: "UZ",
            name: "乌兹别克斯坦"
        }, {
            code: "IR",
            name: "伊朗"
        }, {
            code: "MO",
            name: "澳门"
        }]
    },
    {
        label: "东南亚地区",
        options: [{
            code: "SG",
            name: "新加坡"
        }, {
            code: "VN",
            name: "越南"
        }, {
            code: "PH",
            name: "菲律宾"
        }, {
            code: "MY",
            name: "马来西亚"
        }, {
            code: "BN",
            name: "文莱"
        }, {
            code: "KH",
            name: "柬埔寨"
        }, {
            code: "LA",
            name: "老挝"
        }, {
            code: "MM",
            name: "缅甸"
        }, {
            code: "ID",
            name: "印度尼西亚(印尼)"
        }, {
            code: "MV",
            name: "马尔代夫"
        }, {
            code: "TL",
            name: "东帝汶"
        }]
    },
    {
        label: "非洲地区",
        options: [{
            code: "BF",
            name: "布基纳法索"
        }, {
            code: "CD",
            name: "刚果(金)"
        }, {
            code: "CG",
            name: "刚果(布)"
        }, {
            code: "TD",
            name: "乍得"
        }, {
            code: "DZ",
            name: "阿尔及利亚"
        }, {
            code: "GM",
            name: "冈比亚"
        }, {
            code: "SC",
            name: "塞舌尔"
        }, {
            code: "TG",
            name: "多哥"
        }, {
            code: "GN",
            name: "几内亚"
        }, {
            code: "SD",
            name: "苏丹"
        }, {
            code: "LR",
            name: "利比里亚"
        }, {
            code: "MU",
            name: "毛里求斯"
        }, {
            code: "BI",
            name: "布隆迪"
        }, {
            code: "EG",
            name: "埃及"
        }, {
            code: "LS",
            name: "莱索托"
        }, {
            code: "BJ",
            name: "贝宁"
        }, {
            code: "CM",
            name: "喀麦隆"
        }, {
            code: "MW",
            name: "马拉维"
        }, {
            code: "TN",
            name: "突尼斯"
        }, {
            code: "ET",
            name: "埃塞俄比亚"
        }, {
            code: "ZA",
            name: "南非"
        }, {
            code: "KE",
            name: "肯尼亚"
        }, {
            code: "ZM",
            name: "赞比亚"
        }, {
            code: "SL",
            name: "塞拉利昂"
        }, {
            code: "ZR",
            name: "扎伊尔"
        }, {
            code: "LY",
            name: "利比亚"
        }, {
            code: "AO",
            name: "安哥拉"
        }, {
            code: "ZW",
            name: "津巴布韦"
        }, {
            code: "MA",
            name: "摩洛哥"
        }, {
            code: "NA",
            name: "纳米比亚"
        }, {
            code: "SN",
            name: "塞内加尔"
        }, {
            code: "GA",
            name: "加蓬"
        }, {
            code: "NE",
            name: "尼日尔"
        }, {
            code: "SO",
            name: "索马里"
        }, {
            code: "TZ",
            name: "坦桑尼亚"
        }, {
            code: "CI",
            name: "科特迪瓦共和国"
        }, {
            code: "NG",
            name: "尼日利亚"
        }, {
            code: "BW",
            name: "博茨瓦纳"
        }, {
            code: "MG",
            name: "马达加斯加"
        }, {
            code: "ST",
            name: "圣多美和普林西比"
        }, {
            code: "ML",
            name: "马里"
        }, {
            code: "DJ",
            name: "吉布提"
        }, {
            code: "GH",
            name: "加纳"
        }, {
            code: "CF",
            name: "中非共和国"
        }, {
            code: "SZ",
            name: "斯威士兰"
        }, {
            code: "MZ",
            name: "莫桑比克"
        }]
    },
    {
        label: "美洲地区",
        options: [{
            code: "CA",
            name: "加拿大"
        }, {
            code: "CL",
            name: "智利"
        }, {
            code: "VC",
            name: "圣文森特岛"
        }, {
            code: "MS",
            name: "蒙特塞拉特岛"
        }, {
            code: "EC",
            name: "厄瓜多尔"
        }, {
            code: "VE",
            name: "委内瑞拉"
        }, {
            code: "PA",
            name: "巴拿马"
        }, {
            code: "JM",
            name: "牙买加"
        }, {
            code: "PE",
            name: "秘鲁"
        }, {
            code: "GT",
            name: "危地马拉"
        }, {
            code: "AG",
            name: "安提瓜和巴布达"
        }, {
            code: "GY",
            name: "圭亚那"
        }, {
            code: "MX",
            name: "墨西哥"
        }, {
            code: "AI",
            name: "安圭拉岛"
        }, {
            code: "BM",
            name: "百慕大群岛"
        }, {
            code: "CO",
            name: "哥伦比亚"
        }, {
            code: "CR",
            name: "哥斯达黎加"
        }, {
            code: "HN",
            name: "洪都拉斯"
        }, {
            code: "BO",
            name: "玻利维亚"
        }, {
            code: "TT",
            name: "特立尼达和多巴哥"
        }, {
            code: "HT",
            name: "海地"
        }, {
            code: "AR",
            name: "阿根廷"
        }, {
            code: "PR",
            name: "波多黎各"
        }, {
            code: "CU",
            name: "古巴"
        }, {
            code: "BS",
            name: "巴哈马"
        }, {
            code: "PY",
            name: "巴拉圭"
        }, {
            code: "SR",
            name: "苏里南"
        }, {
            code: "GD",
            name: "格林纳达"
        }, {
            code: "NI",
            name: "尼加拉瓜"
        }, {
            code: "BB",
            name: "巴巴多斯"
        }, {
            code: "BZ",
            name: "伯利兹"
        }, {
            code: "SV",
            name: "萨尔瓦多"
        }, {
            code: "GF",
            name: "法属圭亚那"
        }, {
            code: "UY",
            name: "乌拉圭"
        }, {
            code: "DO",
            name: "多米尼加共和国"
        }, {
            code: "LC",
            name: "圣卢西亚"
        }]
    },
    {
        label: "大洋洲地区",
        options: [{
            code: "AU",
            name: "澳大利亚"
        }, {
            code: "SB",
            name: "所罗门群岛"
        }, {
            code: "NZ",
            name: "新西兰"
        }, {
            code: "FJ",
            name: "斐济"
        }, {
            code: "PF",
            name: "法属玻利尼西亚"
        }, {
            code: "PG",
            name: "巴布亚新几内亚"
        }, {
            code: "TO",
            name: "汤加"
        }, {
            code: "NR",
            name: "瑙鲁"
        }]
    },
    {
        label: "其他地区",
        options: [{
            code: "CK",
            name: "库克群岛"
        }, {
            code: "AZ",
            name: "阿塞拜疆"
        }, {
            code: "KZ",
            name: "哈萨克斯坦"
        }]
    }
]

/**
 * 地区数据
 * 数据格式转换为{[code]:name,...}
 */
export type Region = {
    [code: string]: string
}
export const regions: Region = regionGroups.flatMap(group => group.options).reduce((acc, region) => ({...acc, [region.code]: region.name}), {});
